server:
  port: 8001

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://discovery-service:8761/eureka/

spring:
  application:
    name: store-gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalTrackerFilter
          args:
            baseMessage: Spring Cloud Gateway Global Tracker Filter
            preLogger: true
            postLogger: true
      routes:
        - id: store-user-service
          uri: lb://STORE-USER-SERVICE
          predicates:
            - Path=/store-user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/store-user-service/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: store-user-service
                fallbackuri: forward:/fallback/user
        - id: mileage-service-provide
          uri: lb://MILEAGE-SERVICE
          predicates:
            - Path=/mileage-service/provide/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/mileage-service/(?<segment>.*), /$\{segment}
            - name: CircuitBreaker
              args:
                name: mileage-service
                fallbackuri: forward:/fallback/mileage
        - id: mileage-service-other
          uri: lb://MILEAGE-SERVICE
          predicates:
            - Path=/mileage-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/mileage-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - name: CircuitBreaker
              args:
                name: mileage-service
                fallbackuri: forward:/fallback/mileage

management:
  endpoints:
    web:
      exposure:
        include: health, info

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa